config/routes.rb
Fips::Application.routes.draw do
  resources :orgs do
    resources :org_addresses
    resources :org_telefphones
    resources :tz_requests do
      resources :fips_tzs do
        member do
          get "create_docx" => "fips_tzs#create_docx", format: 'docx'
        end
      end
    end
  end
#  netzke
  devise_for :users, :controllers => {
    :sessions => "users/sessions",
    :registrations => "users/registrations"
  }
  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "users/sign_out", :to => "users/sessions#destroy"
    delete "users/sign_out", :to => "users/sessions#destroy"
    root "users/sessions#new"
  end

  scope "/admin" do
    resources :users
  end


  resources :proxies
  resources :fips_tzs do
    member do
      get "create_docx" => "fips_tzs#create_docx", format: 'docx'
    end
  end
  get "/noko/:id" => "fips_tzs#noko", as: :fips_noko
  get "/update_all" => "fips_tzs#update_all"
  get "/fips/:id" => "fips_tzs#fips_show"
  get "/update_tz/:id" => "fips_tzs#update_tz"
  get "fips_adm" => "fips_tzs#fips_adm"
  get "home/index"
  get "home/kachalka"
  get "/tz_number_generate" => "fips_tzs#tz_number_generate"
  post "/tz_number_generate" => "fips_tzs#tz_number_generate"
  get "/proxy_load" => "proxies#proxy_load"
  get "/proxy_check" => "proxies#proxy_check"
  get "/fips_kachalka" => "proxies#fips_kachalka"
  get "/check" => "proxies#check"
end

app/models/org.rb
class Org < ApplicationRecord
include ActiveModel::Validations
paginates_per 25
has_many :org_addresses
has_many :org_telefphones
end

app/controllers/orgs_controller.rb
class OrgsController < ApplicationController
  before_action :set_org, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @orgs = Org.all
    respond_with(@orgs)
  end

  def show
    respond_with(@org)
  end

  def new
    @org = Org.new
    respond_with(@org)
  end

  def edit
  end

  def create
    @org = Org.new(org_params)
    @org.save
    respond_with(@org)
  end

  def update
    @org.update(org_params)
    respond_with(@org)
  end

  def destroy
    @org.destroy
    respond_with(@org)
  end

  private
    def set_org
      @org = Org.find(params[:id])
    end

    def org_params
      params.require(:org).permit(:shortname, :fullname, :create, :org_state_id)
    end
end

app/helpers/orgs_helper.rb
module OrgsHelper
end

app/views/orgs/_form.html.haml
= form_for @org,  :html => { :class => 'form form-horizontal' } do |f|
  - if @org.errors.any?
    #error_explanation
      %h2= "#{pluralize(@org.errors.count, "error")} prohibited this org from being saved:"
      %ul
        - @org.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :shortname, :class => 'control-label'
    .controls
      = f.text_field :shortname, class: "form-control", required: true
  .form-group
    = f.label :fullname, :class => 'control-label'
    .controls
      = f.text_field :fullname, class: "form-control", required: true
  .form-group
    = f.label :create, :class => 'control-label'
    .controls
      = f.date_select :create, class: "form-control", required: true
  .form-group
    = f.label :org_state_id, :class => 'control-label'
    .controls
      = f.number_field :org_state_id, class: "form-control", required: true
  = f.submit nil, :class => 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), orgs_path, :class => 'btn btn-default'
  = link_to t('.back', :default => t("helpers.links.back")), :back, :class => 'btn btn-default'

app/views/orgs/edit.html.haml
%h1 Editing org
= render 'form'
= link_to 'Show', @org
= link_to 'Back', :back

app/views/orgs/index.html.haml
- model_class = Org
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize

%h1 Listing orgs

%table.table.table-striped.table-hover.table-condensed
  %thead
    %tr
      %th Shortname
      %th Fullname
      %th Create
      %th Org state
      %th
      %th
      %th

  %tbody
    - @orgs.each do |org|
      %tr
        %td= org.shortname
        %td= org.fullname
        %td= org.create
        %td= org.org_state_id
        %td= link_to 'Show', org
        %td= link_to 'Edit', edit_org_path(org)
        %td= link_to 'Destroy', org, :method => :delete, :data => { :confirm => 'Are you sure?' }

= link_to t('.new', :default => t("helpers.links.new")), new_org_path, :class => 'btn btn-primary'

app/views/orgs/new.html.haml
%h1 New org

= render 'form'
= link_to 'Back', :back

app/views/orgs/show.html.haml
%p#notice= notice

%p
  %b Shortname:
  = @org.shortname
%p
  %b Fullname:
  = @org.fullname
%p
  %b Create:
  = @org.create
%p
  %b Org state:
  = @org.org_state_id

= link_to 'Edit', edit_org_path(@org)
\|
= link_to 'Back', orgs_path