config/routes.rb
Fips::Application.routes.draw do
  resources :orgs do
    resources :org_addresses
    resources :org_telefphones
    resources :tz_requests do
      resources :fips_tzs do
        member do
          get "create_docx" => "fips_tzs#create_docx", format: 'docx'
        end
      end
    end
  end
#  netzke
  devise_for :users, :controllers => {
    :sessions => "users/sessions",
    :registrations => "users/registrations"
  }
  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "users/sign_out", :to => "users/sessions#destroy"
    delete "users/sign_out", :to => "users/sessions#destroy"
    root "users/sessions#new"
  end

  scope "/admin" do
    resources :users
  end


  resources :proxies
  resources :fips_tzs do
    member do
      get "create_docx" => "fips_tzs#create_docx", format: 'docx'
    end
  end
  get "/noko/:id" => "fips_tzs#noko", as: :fips_noko
  get "/update_all" => "fips_tzs#update_all"
  get "/fips/:id" => "fips_tzs#fips_show"
  get "/update_tz/:id" => "fips_tzs#update_tz"
  get "fips_adm" => "fips_tzs#fips_adm"
  get "home/index"
  get "home/kachalka"
  get "/tz_number_generate" => "fips_tzs#tz_number_generate"
  post "/tz_number_generate" => "fips_tzs#tz_number_generate"
  get "/proxy_load" => "proxies#proxy_load"
  get "/proxy_check" => "proxies#proxy_check"
  get "/fips_kachalka" => "proxies#fips_kachalka"
  get "/check" => "proxies#check"
end

app/controllers/org_addresses_controller.rb
class OrgAddressesController < ApplicationController
  before_action :set_org_address, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @org_addresses = OrgAddress.all
    respond_with(@org_addresses)
  end

  def show
    respond_with(@org_address)
  end

  def new
    @org_address = OrgAddress.new
    respond_with(@org_address)
  end

  def edit
  end

  def create
    @org_address = OrgAddress.new(org_address_params)
    @org_address.save
    respond_with(@org_address)
  end

  def update
    @org_address.update(org_address_params)
    respond_with(@org_address)
  end

  def destroy
    @org_address.destroy
    respond_with(@org_address)
  end

  private
    def set_org_address
      @org_address = OrgAddress.find(params[:id])
    end

    def org_address_params
      params.require(:org_address).permit(:org_id, :address)
    end
end

app/helpers/org_addresses_helper.rb
module OrgAddressesHelper
end

app/views/org_addresses/_form.html.haml
= form_for @org_address,  :html => { :class => 'form form-horizontal' } do |f|
  - if @org_address.errors.any?
    #error_explanation
      %h2= "#{pluralize(@org_address.errors.count, "error")} prohibited this org_address from being saved:"
      %ul
        - @org_address.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :org_id, :class => 'control-label'
    .controls
      = f.number_field :org_id, class: "form-control", required: true
  .form-group
    = f.label :address, :class => 'control-label'
    .controls
      = f.text_field :address, class: "form-control", required: true
  = f.submit nil, :class => 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), org_addresses_path, :class => 'btn btn-default'
  = link_to t('.back', :default => t("helpers.links.back")), :back, :class => 'btn btn-default'

app/views/org_addresses/edit.html.haml
%h1 Editing org_address
= render 'form'
= link_to 'Show', @org_address
= link_to 'Back', :back

app/views/org_addresses/index.html.haml
- model_class = OrgAddress
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize

%h1 Listing org_addresses

%table.table.table-striped.table-hover.table-condensed
  %thead
    %tr
      %th Org
      %th Address
      %th
      %th
      %th

  %tbody
    - @org_addresses.each do |org_address|
      %tr
        %td= org_address.org_id
        %td= org_address.address
        %td= link_to 'Show', org_address
        %td= link_to 'Edit', edit_org_address_path(org_address)
        %td= link_to 'Destroy', org_address, :method => :delete, :data => { :confirm => 'Are you sure?' }

= link_to t('.new', :default => t("helpers.links.new")), new_org_address_path, :class => 'btn btn-primary'

app/views/org_addresses/new.html.haml
%h1 New org_address

= render 'form'
= link_to 'Back', :back

app/views/org_addresses/show.html.haml
%p#notice= notice

%p
  %b Org:
  = @org_address.org_id
%p
  %b Address:
  = @org_address.address

= link_to 'Edit', edit_org_address_path(@org_address)
\|
= link_to 'Back', org_addresses_path