config/routes.rb
Fips::Application.routes.draw do
  resources :orgs do
    resources :org_addresses
    resources :org_telefphones
    resources :tz_requests do
      resources :fips_tzs do
        member do
          get "create_docx" => "fips_tzs#create_docx", format: 'docx'
        end
      end
    end
  end
#  netzke
  devise_for :users, :controllers => {
    :sessions => "users/sessions",
    :registrations => "users/registrations"
  }
  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "users/sign_out", :to => "users/sessions#destroy"
    delete "users/sign_out", :to => "users/sessions#destroy"
    root "users/sessions#new"
  end

  scope "/admin" do
    resources :users
  end


  resources :proxies
  resources :fips_tzs do
    member do
      get "create_docx" => "fips_tzs#create_docx", format: 'docx'
    end
  end
  get "/noko/:id" => "fips_tzs#noko", as: :fips_noko
  get "/update_all" => "fips_tzs#update_all"
  get "/fips/:id" => "fips_tzs#fips_show"
  get "/update_tz/:id" => "fips_tzs#update_tz"
  get "fips_adm" => "fips_tzs#fips_adm"
  get "home/index"
  get "home/kachalka"
  get "/tz_number_generate" => "fips_tzs#tz_number_generate"
  post "/tz_number_generate" => "fips_tzs#tz_number_generate"
  get "/proxy_load" => "proxies#proxy_load"
  get "/proxy_check" => "proxies#proxy_check"
  get "/fips_kachalka" => "proxies#fips_kachalka"
  get "/check" => "proxies#check"
end

app/models/tz_request.rb
class TzRequest < ApplicationRecord
include ActiveModel::Validations
paginates_per 25
end

app/controllers/tz_requests_controller.rb
class TzRequestsController < ApplicationController
  before_action :set_tz_request, only: [:show, :edit, :update, :destroy]

  # GET /tz_requests
  def index
    @tz_requests = TzRequest.all.order(sort_column + " " + sort_direction).page(params[:page]).per(params[:limit])
    authorize @tz_requests
    respond_with @tz_requests
  end

  # GET /tz_requests/1
  def show
    authorize @tz_request
    respond_with @tz_request
  end

  # GET /tz_requests/new
  def new
    @tz_request = TzRequest.new
    authorize @tz_request
    respond_with @tz_request
  end

  # GET /tz_requests/1/edit
  def edit
    authorize @tz_request
  end

  # POST /tz_requests
  def create
    @tz_request = TzRequest.new(tz_request_params)
    authorize @tz_request
    flash[:notice] =  'The tz_request was successfully saved!' if @tz_request.save && !request.xhr?
    respond_with @tz_request
  end

  # PATCH/PUT /tz_requests/1
  def update
    @tz_request.update(tz_request_params)
    authorize @tz_request
    flash[:notice] =  'The tz_request was successfully updated!' if @tz_request.update(tz_request_params) && !request.xhr?
    respond_with @tz_request
  end

  # DELETE /tz_requests/1
  def destroy
    authorize @tz_request
    redirect_to tz_requests_url, notice: 'Tz request was successfully destroyed.'  if @tz_request.destroy && !request.xhr?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tz_request
      @tz_request = TzRequest.find(params[:id])
    end

    def sort_column
      TzRequest.all.column_names.include?(params[:sort]) ? params[:sort] : "id"
    end


    # Only allow a trusted parameter "white list" through.
    def tz_request_params
      params.require(:tz_request).permit(:date_start, :doc, :org_id, :img)
    end
end

app/helpers/tz_requests_helper.rb
module TzRequestsHelper
end

app/views/tz_requests/_form.html.haml
= form_for @tz_request,  :html => { :class => 'form form-horizontal' } do |f|
  - if @tz_request.errors.any?
    #error_explanation
      %h2= "#{pluralize(@tz_request.errors.count, "error")} prohibited this tz_request from being saved:"
      %ul
        - @tz_request.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :date_start, :class => 'control-label'
    .controls
      = f.date_select :date_start, class: "form-control", required: true
  .form-group
    = f.label :doc, :class => 'control-label'
    .controls
      = f.text_field :doc, class: "form-control", required: true
  .form-group
    = f.label :org_id, :class => 'control-label'
    .controls
      = f.number_field :org_id, class: "form-control", required: true
  .form-group
    = f.label :img, :class => 'control-label'
    .controls
      = f.text_field :img, class: "form-control", required: true
  = f.submit nil, :class => 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), tz_requests_path, :class => 'btn btn-default'
  = link_to t('.back', :default => t("helpers.links.back")), :back, :class => 'btn btn-default'

app/views/tz_requests/edit.html.haml
%h1 Editing tz_request
= render 'form'
= link_to 'Show', @tz_request
= link_to 'Back', :back

app/views/tz_requests/index.html.haml
- model_class = TzRequest
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize

%h1 Listing tz_requests

%table.table.table-striped.table-hover.table-condensed
  %thead
    %tr
      %th Date start
      %th Doc
      %th Org
      %th Img
      %th
      %th
      %th

  %tbody
    - @tz_requests.each do |tz_request|
      %tr
        %td= tz_request.date_start
        %td= tz_request.doc
        %td= tz_request.org_id
        %td= tz_request.img
        %td= link_to 'Show', tz_request
        %td= link_to 'Edit', edit_tz_request_path(tz_request)
        %td= link_to 'Destroy', tz_request, :method => :delete, :data => { :confirm => 'Are you sure?' }

= link_to t('.new', :default => t("helpers.links.new")), new_tz_request_path, :class => 'btn btn-primary'

app/views/tz_requests/new.html.haml
%h1 New tz_request

= render 'form'
= link_to 'Back', :back

app/views/tz_requests/show.html.haml
%p#notice= notice

%p
  %b Date start:
  = @tz_request.date_start
%p
  %b Doc:
  = @tz_request.doc
%p
  %b Org:
  = @tz_request.org_id
%p
  %b Img:
  = @tz_request.img

= link_to 'Edit', edit_tz_request_path(@tz_request)
\|
= link_to 'Back', tz_requests_path